name: check Next.js app

on:
    push:
        branches: ['main']

jobs:
    code-check:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - uses: npm/action-setup@v3
              name: 'Install Deps'
              run: npm install
            - name: 'Check'
              run: npm check:all

    # npm run test
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        permissions:
            contents: read
            pull-requests: write

        steps:
            - uses: actions/checkout@v4
            - name: 'Install Node'
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - name: 'Install Deps'
              run: npm install
            - name: 'Test'
              run: npx vitest --coverage.enabled true
            - name: 'Report Coverage'
              if: always()
              uses: davelosert/vitest-coverage-report-action@v2
